"""
Prometheus metrics for the LLM backend.
Exposed at /metrics via prometheus_client.
"""

from prometheus_client import Counter, Histogram, Gauge, Info

REQUEST_COUNT = Counter(
    "llm_request_total",
    "Total chat requests",
    ["status"],  # success | error
)

INFERENCE_LATENCY = Histogram(
    "llm_inference_duration_seconds",
    "Time spent generating a response",
    buckets=[0.1, 0.5, 1, 2, 5, 10, 30],
)

TOKENS_GENERATED = Counter(
    "llm_tokens_generated_total",
    "Total tokens generated by model",
)

MODEL_INFO = Info("llm_model", "Current model metadata")

MODEL_VERSION_GAUGE = Gauge(
    "llm_model_version",
    "Numeric model version (1=v1, 2=v2 ...)",
)


def set_model_info(model_name: str, model_version: str) -> None:
    """Call once at startup after model is loaded."""
    MODEL_INFO.info({"name": model_name, "version": model_version})
    try:
        numeric = int("".join(filter(str.isdigit, model_version)))
    except ValueError:
        numeric = 0
    MODEL_VERSION_GAUGE.set(numeric)
